// Code generated by "enumer -type LCMState -linecomment -text"; DO NOT EDIT.

package cloud

import (
	"fmt"
	"strings"
)

const (
	_LCMStateName_0      = "initprologbootrunningmigratesave_stopsave_suspendsave_migrateprolog_migrateprolog_resumeepilog_stopepilogshutdown"
	_LCMStateLowerName_0 = "initprologbootrunningmigratesave_stopsave_suspendsave_migrateprolog_migrateprolog_resumeepilog_stopepilogshutdown"
	_LCMStateName_1      = "cleanup_resubmitunknownhotplugshutdown_poweroffboot_unknownboot_poweroffboot_suspendedboot_stoppedcleanup_deletehotplug_snapshothotplug_nichotplug_saveashotplug_saveas_poweroffhotplug_saveas_suspendedshutdown_undeployepilog_undeployprolog_undeployboot_undeployhotplug_prolog_poweroffhotplug_epilog_poweroffboot_migrateboot_failureboot_migrate_failureprolog_migrate_failureprolog_failureepilog_failureepilog_stop_failureepilog_undeploy_failureprolog_migrate_poweroffprolog_migrate_poweroff_failureprolog_migrate_suspendprolog_migrate_suspend_failureboot_undeploy_failureboot_stopped_failureprolog_resume_failureprolog_undeploy_failuredisk_snapshot_poweroffdisk_snapshot_revert_poweroffdisk_snapshot_delete_poweroffdisk_snapshot_suspenddisk_snapshot_revert_suspendeddisk_snapshot_delete_suspendeddisk_snapshot"
	_LCMStateLowerName_1 = "cleanup_resubmitunknownhotplugshutdown_poweroffboot_unknownboot_poweroffboot_suspendedboot_stoppedcleanup_deletehotplug_snapshothotplug_nichotplug_saveashotplug_saveas_poweroffhotplug_saveas_suspendedshutdown_undeployepilog_undeployprolog_undeployboot_undeployhotplug_prolog_poweroffhotplug_epilog_poweroffboot_migrateboot_failureboot_migrate_failureprolog_migrate_failureprolog_failureepilog_failureepilog_stop_failureepilog_undeploy_failureprolog_migrate_poweroffprolog_migrate_poweroff_failureprolog_migrate_suspendprolog_migrate_suspend_failureboot_undeploy_failureboot_stopped_failureprolog_resume_failureprolog_undeploy_failuredisk_snapshot_poweroffdisk_snapshot_revert_poweroffdisk_snapshot_delete_poweroffdisk_snapshot_suspenddisk_snapshot_revert_suspendeddisk_snapshot_delete_suspendeddisk_snapshot"
	_LCMStateName_2      = "disk_snapshot_deleteprolog_migrate_unknownprolog_migrate_unknown_failure"
	_LCMStateLowerName_2 = "disk_snapshot_deleteprolog_migrate_unknownprolog_migrate_unknown_failure"
)

var (
	_LCMStateIndex_0 = [...]uint8{0, 4, 10, 14, 21, 28, 37, 49, 61, 75, 88, 99, 105, 113}
	_LCMStateIndex_1 = [...]uint16{0, 16, 23, 30, 47, 59, 72, 86, 98, 112, 128, 139, 153, 176, 200, 217, 232, 247, 260, 283, 306, 318, 330, 350, 372, 386, 400, 419, 442, 465, 496, 518, 548, 569, 589, 610, 633, 655, 684, 713, 734, 764, 794, 807}
	_LCMStateIndex_2 = [...]uint8{0, 20, 42, 72}
)

func (i LCMState) String() string {
	switch {
	case 0 <= i && i <= 12:
		return _LCMStateName_0[_LCMStateIndex_0[i]:_LCMStateIndex_0[i+1]]
	case 15 <= i && i <= 57:
		i -= 15
		return _LCMStateName_1[_LCMStateIndex_1[i]:_LCMStateIndex_1[i+1]]
	case 59 <= i && i <= 61:
		i -= 59
		return _LCMStateName_2[_LCMStateIndex_2[i]:_LCMStateIndex_2[i+1]]
	default:
		return fmt.Sprintf("LCMState(%d)", i)
	}
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _LCMStateNoOp() {
	var x [1]struct{}
	_ = x[InitLCMState-(0)]
	_ = x[PrologLCMState-(1)]
	_ = x[BootLCMState-(2)]
	_ = x[RunningLCMState-(3)]
	_ = x[MigrateLCMState-(4)]
	_ = x[SaveStopLCMState-(5)]
	_ = x[SaveSuspendLCMState-(6)]
	_ = x[SaveMigrateLCMState-(7)]
	_ = x[PrologMigrateLCMState-(8)]
	_ = x[PrologResumeLCMState-(9)]
	_ = x[EpilogStopLCMState-(10)]
	_ = x[EpilogLCMState-(11)]
	_ = x[ShutdownLCMState-(12)]
	_ = x[CleanupResubmitLCMState-(15)]
	_ = x[UnknownLCMState-(16)]
	_ = x[HotplugLCMState-(17)]
	_ = x[ShutdownPowerOffLCMState-(18)]
	_ = x[BootUnknownLCMState-(19)]
	_ = x[BootPowerOffLCMState-(20)]
	_ = x[BootSuspendedLCMState-(21)]
	_ = x[BootStoppedLCMState-(22)]
	_ = x[CleanupDeleteLCMState-(23)]
	_ = x[HotplugSnapshotLCMState-(24)]
	_ = x[HotplugNICLCMState-(25)]
	_ = x[HotplugSaveAsLCMState-(26)]
	_ = x[HotplugSaveAsPowerOffLCMState-(27)]
	_ = x[HotplutSaveAsSuspendedLCMState-(28)]
	_ = x[ShutdownUndeployLCMState-(29)]
	_ = x[EpilogUndeployLCMState-(30)]
	_ = x[PrologUndeployLCMState-(31)]
	_ = x[BootUndeployLCMState-(32)]
	_ = x[HotplugPrologPowerOffLCMState-(33)]
	_ = x[HotplugEpilogPowerOffLCMState-(34)]
	_ = x[BootMigrateLCMState-(35)]
	_ = x[BootFailureLCMState-(36)]
	_ = x[BootMigrateFailureLCMState-(37)]
	_ = x[PrologMigrateFailureLCMState-(38)]
	_ = x[PrologFailureLCMState-(39)]
	_ = x[EpilogFailureLCMState-(40)]
	_ = x[EpilogStopFailureLCMState-(41)]
	_ = x[EpilogUndeployFailureLCMState-(42)]
	_ = x[PrologMigratePowerOffLCMState-(43)]
	_ = x[PrologMigratePowerOffFailureLCMState-(44)]
	_ = x[PrologMigrageSuspendLCMState-(45)]
	_ = x[PrologMigrageSuspendFailureLCMState-(46)]
	_ = x[BootUndeployFailureLCMState-(47)]
	_ = x[BootStoppedFailureLCMState-(48)]
	_ = x[PrologResumeFailureLCMState-(49)]
	_ = x[PrologUndeployFailureLCMState-(50)]
	_ = x[DiskSnapshotPowerOffLCMState-(51)]
	_ = x[DiskSnapshotRevertPowerOffLCMState-(52)]
	_ = x[DiskSnapshotDeletePowerOffLCMState-(53)]
	_ = x[DiskSnapshotSuspendLCMState-(54)]
	_ = x[DiskSnapshotRevertSuspendedLCMState-(55)]
	_ = x[DiskSnapshotDeleteSuspendedLCMState-(56)]
	_ = x[DiskSnapshotLCMState-(57)]
	_ = x[DiskSnapshotDeleteLCMState-(59)]
	_ = x[PrologMigrateUnknownLCMState-(60)]
	_ = x[PrologMigrateUnknownFailureLCMState-(61)]
}

var _LCMStateValues = []LCMState{InitLCMState, PrologLCMState, BootLCMState, RunningLCMState, MigrateLCMState, SaveStopLCMState, SaveSuspendLCMState, SaveMigrateLCMState, PrologMigrateLCMState, PrologResumeLCMState, EpilogStopLCMState, EpilogLCMState, ShutdownLCMState, CleanupResubmitLCMState, UnknownLCMState, HotplugLCMState, ShutdownPowerOffLCMState, BootUnknownLCMState, BootPowerOffLCMState, BootSuspendedLCMState, BootStoppedLCMState, CleanupDeleteLCMState, HotplugSnapshotLCMState, HotplugNICLCMState, HotplugSaveAsLCMState, HotplugSaveAsPowerOffLCMState, HotplutSaveAsSuspendedLCMState, ShutdownUndeployLCMState, EpilogUndeployLCMState, PrologUndeployLCMState, BootUndeployLCMState, HotplugPrologPowerOffLCMState, HotplugEpilogPowerOffLCMState, BootMigrateLCMState, BootFailureLCMState, BootMigrateFailureLCMState, PrologMigrateFailureLCMState, PrologFailureLCMState, EpilogFailureLCMState, EpilogStopFailureLCMState, EpilogUndeployFailureLCMState, PrologMigratePowerOffLCMState, PrologMigratePowerOffFailureLCMState, PrologMigrageSuspendLCMState, PrologMigrageSuspendFailureLCMState, BootUndeployFailureLCMState, BootStoppedFailureLCMState, PrologResumeFailureLCMState, PrologUndeployFailureLCMState, DiskSnapshotPowerOffLCMState, DiskSnapshotRevertPowerOffLCMState, DiskSnapshotDeletePowerOffLCMState, DiskSnapshotSuspendLCMState, DiskSnapshotRevertSuspendedLCMState, DiskSnapshotDeleteSuspendedLCMState, DiskSnapshotLCMState, DiskSnapshotDeleteLCMState, PrologMigrateUnknownLCMState, PrologMigrateUnknownFailureLCMState}

var _LCMStateNameToValueMap = map[string]LCMState{
	_LCMStateName_0[0:4]:          InitLCMState,
	_LCMStateLowerName_0[0:4]:     InitLCMState,
	_LCMStateName_0[4:10]:         PrologLCMState,
	_LCMStateLowerName_0[4:10]:    PrologLCMState,
	_LCMStateName_0[10:14]:        BootLCMState,
	_LCMStateLowerName_0[10:14]:   BootLCMState,
	_LCMStateName_0[14:21]:        RunningLCMState,
	_LCMStateLowerName_0[14:21]:   RunningLCMState,
	_LCMStateName_0[21:28]:        MigrateLCMState,
	_LCMStateLowerName_0[21:28]:   MigrateLCMState,
	_LCMStateName_0[28:37]:        SaveStopLCMState,
	_LCMStateLowerName_0[28:37]:   SaveStopLCMState,
	_LCMStateName_0[37:49]:        SaveSuspendLCMState,
	_LCMStateLowerName_0[37:49]:   SaveSuspendLCMState,
	_LCMStateName_0[49:61]:        SaveMigrateLCMState,
	_LCMStateLowerName_0[49:61]:   SaveMigrateLCMState,
	_LCMStateName_0[61:75]:        PrologMigrateLCMState,
	_LCMStateLowerName_0[61:75]:   PrologMigrateLCMState,
	_LCMStateName_0[75:88]:        PrologResumeLCMState,
	_LCMStateLowerName_0[75:88]:   PrologResumeLCMState,
	_LCMStateName_0[88:99]:        EpilogStopLCMState,
	_LCMStateLowerName_0[88:99]:   EpilogStopLCMState,
	_LCMStateName_0[99:105]:       EpilogLCMState,
	_LCMStateLowerName_0[99:105]:  EpilogLCMState,
	_LCMStateName_0[105:113]:      ShutdownLCMState,
	_LCMStateLowerName_0[105:113]: ShutdownLCMState,
	_LCMStateName_1[0:16]:         CleanupResubmitLCMState,
	_LCMStateLowerName_1[0:16]:    CleanupResubmitLCMState,
	_LCMStateName_1[16:23]:        UnknownLCMState,
	_LCMStateLowerName_1[16:23]:   UnknownLCMState,
	_LCMStateName_1[23:30]:        HotplugLCMState,
	_LCMStateLowerName_1[23:30]:   HotplugLCMState,
	_LCMStateName_1[30:47]:        ShutdownPowerOffLCMState,
	_LCMStateLowerName_1[30:47]:   ShutdownPowerOffLCMState,
	_LCMStateName_1[47:59]:        BootUnknownLCMState,
	_LCMStateLowerName_1[47:59]:   BootUnknownLCMState,
	_LCMStateName_1[59:72]:        BootPowerOffLCMState,
	_LCMStateLowerName_1[59:72]:   BootPowerOffLCMState,
	_LCMStateName_1[72:86]:        BootSuspendedLCMState,
	_LCMStateLowerName_1[72:86]:   BootSuspendedLCMState,
	_LCMStateName_1[86:98]:        BootStoppedLCMState,
	_LCMStateLowerName_1[86:98]:   BootStoppedLCMState,
	_LCMStateName_1[98:112]:       CleanupDeleteLCMState,
	_LCMStateLowerName_1[98:112]:  CleanupDeleteLCMState,
	_LCMStateName_1[112:128]:      HotplugSnapshotLCMState,
	_LCMStateLowerName_1[112:128]: HotplugSnapshotLCMState,
	_LCMStateName_1[128:139]:      HotplugNICLCMState,
	_LCMStateLowerName_1[128:139]: HotplugNICLCMState,
	_LCMStateName_1[139:153]:      HotplugSaveAsLCMState,
	_LCMStateLowerName_1[139:153]: HotplugSaveAsLCMState,
	_LCMStateName_1[153:176]:      HotplugSaveAsPowerOffLCMState,
	_LCMStateLowerName_1[153:176]: HotplugSaveAsPowerOffLCMState,
	_LCMStateName_1[176:200]:      HotplutSaveAsSuspendedLCMState,
	_LCMStateLowerName_1[176:200]: HotplutSaveAsSuspendedLCMState,
	_LCMStateName_1[200:217]:      ShutdownUndeployLCMState,
	_LCMStateLowerName_1[200:217]: ShutdownUndeployLCMState,
	_LCMStateName_1[217:232]:      EpilogUndeployLCMState,
	_LCMStateLowerName_1[217:232]: EpilogUndeployLCMState,
	_LCMStateName_1[232:247]:      PrologUndeployLCMState,
	_LCMStateLowerName_1[232:247]: PrologUndeployLCMState,
	_LCMStateName_1[247:260]:      BootUndeployLCMState,
	_LCMStateLowerName_1[247:260]: BootUndeployLCMState,
	_LCMStateName_1[260:283]:      HotplugPrologPowerOffLCMState,
	_LCMStateLowerName_1[260:283]: HotplugPrologPowerOffLCMState,
	_LCMStateName_1[283:306]:      HotplugEpilogPowerOffLCMState,
	_LCMStateLowerName_1[283:306]: HotplugEpilogPowerOffLCMState,
	_LCMStateName_1[306:318]:      BootMigrateLCMState,
	_LCMStateLowerName_1[306:318]: BootMigrateLCMState,
	_LCMStateName_1[318:330]:      BootFailureLCMState,
	_LCMStateLowerName_1[318:330]: BootFailureLCMState,
	_LCMStateName_1[330:350]:      BootMigrateFailureLCMState,
	_LCMStateLowerName_1[330:350]: BootMigrateFailureLCMState,
	_LCMStateName_1[350:372]:      PrologMigrateFailureLCMState,
	_LCMStateLowerName_1[350:372]: PrologMigrateFailureLCMState,
	_LCMStateName_1[372:386]:      PrologFailureLCMState,
	_LCMStateLowerName_1[372:386]: PrologFailureLCMState,
	_LCMStateName_1[386:400]:      EpilogFailureLCMState,
	_LCMStateLowerName_1[386:400]: EpilogFailureLCMState,
	_LCMStateName_1[400:419]:      EpilogStopFailureLCMState,
	_LCMStateLowerName_1[400:419]: EpilogStopFailureLCMState,
	_LCMStateName_1[419:442]:      EpilogUndeployFailureLCMState,
	_LCMStateLowerName_1[419:442]: EpilogUndeployFailureLCMState,
	_LCMStateName_1[442:465]:      PrologMigratePowerOffLCMState,
	_LCMStateLowerName_1[442:465]: PrologMigratePowerOffLCMState,
	_LCMStateName_1[465:496]:      PrologMigratePowerOffFailureLCMState,
	_LCMStateLowerName_1[465:496]: PrologMigratePowerOffFailureLCMState,
	_LCMStateName_1[496:518]:      PrologMigrageSuspendLCMState,
	_LCMStateLowerName_1[496:518]: PrologMigrageSuspendLCMState,
	_LCMStateName_1[518:548]:      PrologMigrageSuspendFailureLCMState,
	_LCMStateLowerName_1[518:548]: PrologMigrageSuspendFailureLCMState,
	_LCMStateName_1[548:569]:      BootUndeployFailureLCMState,
	_LCMStateLowerName_1[548:569]: BootUndeployFailureLCMState,
	_LCMStateName_1[569:589]:      BootStoppedFailureLCMState,
	_LCMStateLowerName_1[569:589]: BootStoppedFailureLCMState,
	_LCMStateName_1[589:610]:      PrologResumeFailureLCMState,
	_LCMStateLowerName_1[589:610]: PrologResumeFailureLCMState,
	_LCMStateName_1[610:633]:      PrologUndeployFailureLCMState,
	_LCMStateLowerName_1[610:633]: PrologUndeployFailureLCMState,
	_LCMStateName_1[633:655]:      DiskSnapshotPowerOffLCMState,
	_LCMStateLowerName_1[633:655]: DiskSnapshotPowerOffLCMState,
	_LCMStateName_1[655:684]:      DiskSnapshotRevertPowerOffLCMState,
	_LCMStateLowerName_1[655:684]: DiskSnapshotRevertPowerOffLCMState,
	_LCMStateName_1[684:713]:      DiskSnapshotDeletePowerOffLCMState,
	_LCMStateLowerName_1[684:713]: DiskSnapshotDeletePowerOffLCMState,
	_LCMStateName_1[713:734]:      DiskSnapshotSuspendLCMState,
	_LCMStateLowerName_1[713:734]: DiskSnapshotSuspendLCMState,
	_LCMStateName_1[734:764]:      DiskSnapshotRevertSuspendedLCMState,
	_LCMStateLowerName_1[734:764]: DiskSnapshotRevertSuspendedLCMState,
	_LCMStateName_1[764:794]:      DiskSnapshotDeleteSuspendedLCMState,
	_LCMStateLowerName_1[764:794]: DiskSnapshotDeleteSuspendedLCMState,
	_LCMStateName_1[794:807]:      DiskSnapshotLCMState,
	_LCMStateLowerName_1[794:807]: DiskSnapshotLCMState,
	_LCMStateName_2[0:20]:         DiskSnapshotDeleteLCMState,
	_LCMStateLowerName_2[0:20]:    DiskSnapshotDeleteLCMState,
	_LCMStateName_2[20:42]:        PrologMigrateUnknownLCMState,
	_LCMStateLowerName_2[20:42]:   PrologMigrateUnknownLCMState,
	_LCMStateName_2[42:72]:        PrologMigrateUnknownFailureLCMState,
	_LCMStateLowerName_2[42:72]:   PrologMigrateUnknownFailureLCMState,
}

var _LCMStateNames = []string{
	_LCMStateName_0[0:4],
	_LCMStateName_0[4:10],
	_LCMStateName_0[10:14],
	_LCMStateName_0[14:21],
	_LCMStateName_0[21:28],
	_LCMStateName_0[28:37],
	_LCMStateName_0[37:49],
	_LCMStateName_0[49:61],
	_LCMStateName_0[61:75],
	_LCMStateName_0[75:88],
	_LCMStateName_0[88:99],
	_LCMStateName_0[99:105],
	_LCMStateName_0[105:113],
	_LCMStateName_1[0:16],
	_LCMStateName_1[16:23],
	_LCMStateName_1[23:30],
	_LCMStateName_1[30:47],
	_LCMStateName_1[47:59],
	_LCMStateName_1[59:72],
	_LCMStateName_1[72:86],
	_LCMStateName_1[86:98],
	_LCMStateName_1[98:112],
	_LCMStateName_1[112:128],
	_LCMStateName_1[128:139],
	_LCMStateName_1[139:153],
	_LCMStateName_1[153:176],
	_LCMStateName_1[176:200],
	_LCMStateName_1[200:217],
	_LCMStateName_1[217:232],
	_LCMStateName_1[232:247],
	_LCMStateName_1[247:260],
	_LCMStateName_1[260:283],
	_LCMStateName_1[283:306],
	_LCMStateName_1[306:318],
	_LCMStateName_1[318:330],
	_LCMStateName_1[330:350],
	_LCMStateName_1[350:372],
	_LCMStateName_1[372:386],
	_LCMStateName_1[386:400],
	_LCMStateName_1[400:419],
	_LCMStateName_1[419:442],
	_LCMStateName_1[442:465],
	_LCMStateName_1[465:496],
	_LCMStateName_1[496:518],
	_LCMStateName_1[518:548],
	_LCMStateName_1[548:569],
	_LCMStateName_1[569:589],
	_LCMStateName_1[589:610],
	_LCMStateName_1[610:633],
	_LCMStateName_1[633:655],
	_LCMStateName_1[655:684],
	_LCMStateName_1[684:713],
	_LCMStateName_1[713:734],
	_LCMStateName_1[734:764],
	_LCMStateName_1[764:794],
	_LCMStateName_1[794:807],
	_LCMStateName_2[0:20],
	_LCMStateName_2[20:42],
	_LCMStateName_2[42:72],
}

// LCMStateString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func LCMStateString(s string) (LCMState, error) {
	if val, ok := _LCMStateNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _LCMStateNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to LCMState values", s)
}

// LCMStateValues returns all values of the enum
func LCMStateValues() []LCMState {
	return _LCMStateValues
}

// LCMStateStrings returns a slice of all String values of the enum
func LCMStateStrings() []string {
	strs := make([]string, len(_LCMStateNames))
	copy(strs, _LCMStateNames)
	return strs
}

// IsALCMState returns "true" if the value is listed in the enum definition. "false" otherwise
func (i LCMState) IsALCMState() bool {
	for _, v := range _LCMStateValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for LCMState
func (i LCMState) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for LCMState
func (i *LCMState) UnmarshalText(text []byte) error {
	var err error
	*i, err = LCMStateString(string(text))
	return err
}
