// Code generated by "enumer -type Status -linecomment -text"; DO NOT EDIT.

package cloud

import (
	"fmt"
	"strings"
)

const _StatusName = "enableddisabledoffline"

var _StatusIndex = [...]uint8{0, 7, 15, 22}

const _StatusLowerName = "enableddisabledoffline"

func (i Status) String() string {
	if i < 0 || i >= Status(len(_StatusIndex)-1) {
		return fmt.Sprintf("Status(%d)", i)
	}
	return _StatusName[_StatusIndex[i]:_StatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _StatusNoOp() {
	var x [1]struct{}
	_ = x[EnabledStatus-(0)]
	_ = x[DisabledStatus-(1)]
	_ = x[OfflineStatus-(2)]
}

var _StatusValues = []Status{EnabledStatus, DisabledStatus, OfflineStatus}

var _StatusNameToValueMap = map[string]Status{
	_StatusName[0:7]:        EnabledStatus,
	_StatusLowerName[0:7]:   EnabledStatus,
	_StatusName[7:15]:       DisabledStatus,
	_StatusLowerName[7:15]:  DisabledStatus,
	_StatusName[15:22]:      OfflineStatus,
	_StatusLowerName[15:22]: OfflineStatus,
}

var _StatusNames = []string{
	_StatusName[0:7],
	_StatusName[7:15],
	_StatusName[15:22],
}

// StatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func StatusString(s string) (Status, error) {
	if val, ok := _StatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _StatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Status values", s)
}

// StatusValues returns all values of the enum
func StatusValues() []Status {
	return _StatusValues
}

// StatusStrings returns a slice of all String values of the enum
func StatusStrings() []string {
	strs := make([]string, len(_StatusNames))
	copy(strs, _StatusNames)
	return strs
}

// IsAStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Status) IsAStatus() bool {
	for _, v := range _StatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for Status
func (i Status) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Status
func (i *Status) UnmarshalText(text []byte) error {
	var err error
	*i, err = StatusString(string(text))
	return err
}
